inherit_from: "configs/mono/agri/base_config.yaml"

Dataset:
  dataset_path: "datasets/agri/val/cam_2"
  use_sky_removal: True  # Enable sky removal using depth_anything masks
  sky_depth_threshold: 0  # Pixels with depth value 0 are sky pixels
  Calibration:
    # Camera intrinsic parameters for ZED camera (estimated)
    # These values are typical for ZED cameras at 1920x1200 resolution
    # You should calibrate your camera for better accuracy
    fx: 737.810037  # Focal length in pixels (estimated for 1920x1200)
    fy: 737.952913  # Focal length in pixels (estimated for 1920x1200)
    cx: 975.080485   # Principal point x (image center)
    cy: 569.797510   # Principal point y (image center)
    k1: -0.007018     # Radial distortion coefficient 1
    k2: 0.000347     # Radial distortion coefficient 2
    p1: -0.001131     # Tangential distortion coefficient 1
    p2: -0.000008     # Tangential distortion coefficient 2
    k3: 0.0     # Radial distortion coefficient 3
    width: 1920
    height: 1200
    depth_scale: 5000.0
    distorted: False  # Set to True if you need distortion correction
